helm:
  parameters:
  - name: image.name
    value: ghcr.io/jimbali/jimba.li
    forcestring: true
  - name: image.tag
    value: main@sha256:9c2669f7f80c59c826e0202055d4b9a13f5ba604bb1b24dfa8f1026acc36e3d5
    forcestring: true
