helm:
  parameters:
  - name: image.name
    value: ghcr.io/jimbali/jimba.li
    forcestring: true
  - name: image.tag
    value: main@sha256:9804bf90efb8f5333b82824126771934a5a931e4b7455e62241bc299ae92be71
    forcestring: true
